repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: forbid-new-submodules
      - id: check-executables-have-shebangs
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Update with the desired prettier version
    hooks:
      - id: prettier
        args: [--write, .]
